name: Client Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    client-build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./app/client

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 22

        - name: Install dependencies
          run: npm install

         # Rollup is needed for CI build since its ubuntu and we are developing mostly on mac
        - name: Install Rollup 
          run: npm i --save-dev @rollup/rollup-linux-x64-gnu

        - name: Build Front End
          run: npm run build
