name: Python Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    # ---------- install uv -------------------------------------------------
    - name: Install uv (fast dependency resolver)
      run: |
        python -m pip install --upgrade pip uv

    # ---------- reproduce locked env --------------------------------------
    - name: Sync project dependencies from uv.lock
      run: |
        uv sync --all-extras
    
  # ---------- run test suite -----------------------------------
    - name: Run tests and generate coverage report
      run: |
        pytest tests/ --cov=app --cov-report=xml

    - name: Upload coverage report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
